#+TITLE: Quotes
#+OPTIONS: ':nil *:t -:t ::t <:t H:6 \n:nil ^:{} arch:headline
#+OPTIONS: author:nil c:nil creator:comment d:(not "LOGBOOK") date:t
#+OPTIONS: e:t email:nil f:t inline:t num:nil p:nil pri:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t toc:nil todo:t |:t
#+CREATOR: Emacs 24.4.1 (Org mode 8.2.10)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export

* Animals
** Dogs

#+BEGIN_QUOTE
Outside of a dog, a book is a man's best friend. Inside of a dog it's too dark to read.[fn:3] ~ Groucho Marx
#+END_QUOTE

* Design

#+BEGIN_QUOTE
The major difference between a thing that might go wrong and a thing that cannot possibly go wrong is that when a thing that cannot possibly go wrong goes wrong it usually turns out to be impossible to get at or repair. [fn:5] ~ Douglas Adams - Mostly Harmless 
#+END_QUOTE

* Science
** Physics

#+BEGIN_QUOTE
Physics is like sex: Sure, it might give some practical results, but that’s not why we do it. ~ Richard Feynman
#+END_QUOTE

* Programming
** Functional Programming

#+BEGIN_QUOTE
OO makes code understandable by encapsultating the moving parts. FP makes code understandable by minimizing moving parts.[fn:2] ~ Michael Feathers
#+END_QUOTE

* Keeping Backup Copies

#+BEGIN_QUOTE
Even if you have no need for a synchronization application, you will still need to
back up your work regularly. Because you are lazy and prone to magical thinking, you
will not do this responsibly by yourself.[fn:1] ~ Kieran Healy
#+END_QUOTE

* Terraforming

#+BEGIN_QUOTE
Biology rather than physical engineering is the only realistic way to do things on a planetary scale.[fn:4] ~ Paul Dear at the MRC Laboratory of Molecular Biology in Cambridge.
#+END_QUOTE

* Footnotes

[fn:1] Healy, Kieran. "Choosing Your Workflow Applications."

[fn:2] [[https://twitter.com/mfeathers/status/29581296216][Feathers, Michael. Twitter]]

[fn:3] http://www.brainyquote.com/quotes/quotes/g/grouchomar137218.html

[fn:4] Build a Mars base with a box of engineered bugs | New Scientist - www.newscientist.com
https://www.newscientist.com/article/mg21628855.100-build-a-mars-base-with-a-box-of-engineered-bugs/?cmpid=RSS%2525257cNSNS%2525257c2012-GLOBAL%2525257conline-news

[fn:5] https://en.m.wikipedia.org/wiki/Technology_in_The_Hitchhiker%27s_Guide_to_the_Galaxy
